<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyExpense extends Model
{
    use HasFactory, SoftDeletes;

    public const METHODS = ['cash', 'bank_transfer', 'mobile_money', 'cheque', 'other'];

    protected $fillable = [
        'expense_number',
        'expense_category_id',
        'vehicle_id',
        'supplier_id',
        'company_debt_id',
        'debt_payment_id',
        'description',
        'amount',
        'expense_date',
        'payment_method',
        'notes',
        'created_by',
    ];

    protected function casts(): array
    {
        return [
            'expense_date' => 'date',
            'amount' => 'decimal:2',
        ];
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(ExpenseCategory::class, 'expense_category_id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class);
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function companyDebt(): BelongsTo
    {
        return $this->belongsTo(CompanyDebt::class);
    }

    public function debtPayment(): BelongsTo
    {
        return $this->belongsTo(DebtPayment::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /** True when this expense was generated by settling a company debt. */
    public function scopeFromDebtPayment(Builder $query): Builder
    {
        return $query->whereNotNull('debt_payment_id');
    }

    public function getIsSystemGeneratedAttribute(): bool
    {
        return ! is_null($this->debt_payment_id);
    }
}
