<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyDebt extends Model
{
    use HasFactory, SoftDeletes;

    public const STATUSES = ['outstanding', 'partially_paid', 'paid', 'overdue', 'cancelled'];

    protected $fillable = [
        'debt_number',
        'supplier_id',
        'expense_category_id',
        'vehicle_id',
        'description',
        'original_amount',
        'remaining_amount',
        'debt_date',
        'due_date',
        'status',
        'notes',
        'created_by',
    ];

    protected function casts(): array
    {
        return [
            'debt_date' => 'date',
            'due_date' => 'date',
            'original_amount' => 'decimal:2',
            'remaining_amount' => 'decimal:2',
        ];
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(ExpenseCategory::class, 'expense_category_id');
    }

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class);
    }

    public function payments(): HasMany
    {
        return $this->hasMany(DebtPayment::class);
    }

    /** Fuel bought on this credit line. */
    public function fuelRecords(): HasMany
    {
        return $this->hasMany(FuelRecord::class);
    }

    /**
     * Expenses generated by paying this debt. A debt on its own is NEVER an
     * expense — only the cash that actually leaves the company is.
     */
    public function expenses(): HasMany
    {
        return $this->hasMany(CompanyExpense::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Company debts an instructor may read.
     *
     * A company debt is money the company owes a supplier; nothing on the table
     * names an instructor, and nothing should — rent, salaries and the rest are
     * none of their business. Two existing relationships do reach them, though,
     * and they are the ones that matter on the floor:
     *
     *   - `vehicle_id`, when the debt was raised against a vehicle assigned to
     *     them (a repair bill on their own car);
     *   - `fuel_records.company_debt_id`, when the debt is the credit for fuel
     *     they themselves took.
     *
     * Everything else stays admin-only.
     */
    public function scopeVisibleTo(Builder $query, User $user): Builder
    {
        if ($user->isAdmin()) {
            return $query;
        }

        if ($user->isInstructor()) {
            $instructorId = $user->instructorId() ?? 0;

            return $query->where(fn (Builder $q) => $q
                ->whereHas('vehicle', fn (Builder $v) => $v->where('vehicles.instructor_id', $instructorId))
                ->orWhereHas('fuelRecords', fn (Builder $f) => $f->where('fuel_records.instructor_id', $instructorId)));
        }

        return $query->whereRaw('1 = 0');
    }

    public function scopeOutstanding(Builder $query): Builder
    {
        return $query->whereIn('status', ['outstanding', 'partially_paid', 'overdue']);
    }

    public function getPaidAmountAttribute(): float
    {
        return round((float) $this->original_amount - (float) $this->remaining_amount, 2);
    }

    public function getIsOverdueAttribute(): bool
    {
        return $this->due_date
            && $this->due_date->isPast()
            && in_array($this->status, ['outstanding', 'partially_paid', 'overdue'], true);
    }

    /** Recalculates remaining_amount and status from the payment ledger. */
    public function recalculate(): void
    {
        if ($this->status === 'cancelled') {
            return;
        }

        $paid = (float) $this->payments()->sum('amount');
        $remaining = round(max((float) $this->original_amount - $paid, 0), 2);

        $status = match (true) {
            $remaining <= 0.001 => 'paid',
            $paid > 0 => 'partially_paid',
            default => 'outstanding',
        };

        if ($status !== 'paid' && $this->due_date && $this->due_date->isPast()) {
            $status = 'overdue';
        }

        $this->forceFill([
            'remaining_amount' => $remaining,
            'status' => $status,
        ])->save();
    }
}
