@extends('layouts.app')
@section('title', $expense->expense_number)
@section('heading', $expense->expense_number)

@php $c = $appSettings['currency_symbol']; @endphp

@section('content')
<div class="card max-w-2xl p-5">
    <dl class="space-y-3 text-sm">
        @foreach ([
            __('Category') => $expense->category?->display_name,
            __('Description') => $expense->description,
            __('Amount') => $c.number_format((float) $expense->amount, 2),
            __('Date') => $expense->expense_date?->format('d/m/Y'),
            __('Payment Method') => __(ucwords(str_replace('_', ' ', $expense->payment_method))),
            __('Vehicle') => $expense->vehicle?->plate_number ?? '—',
            __('Supplier') => $expense->supplier?->name ?? '—',
            __('Created By') => $expense->creator?->name ?? '—',
            __('Notes') => $expense->notes ?: '—',
        ] as $label => $value)
            <div class="flex justify-between gap-3">
                <dt class="text-slate-500">{{ $label }}</dt>
                <dd class="text-right font-medium text-slate-800">{{ $value }}</dd>
            </div>
        @endforeach
    </dl>

    @if ($expense->companyDebt)
        <div class="mt-5 rounded-lg border border-brand-200 bg-brand-50 p-4 text-sm">
            <p class="font-semibold text-brand-800">{{ __('Generated by a debt payment') }}</p>
            <p class="mt-1 text-brand-700">
                {{ __('This expense records the cash paid against debt :number.', ['number' => $expense->companyDebt->debt_number]) }}
            </p>
            <a href="{{ route('admin.debts.show', $expense->companyDebt) }}" class="btn-secondary btn-sm mt-3">{{ __('View debt') }}</a>
        </div>
    @endif

    <div class="mt-5 flex gap-2">
        @unless ($expense->is_system_generated)
            <a href="{{ route('admin.expenses.edit', $expense) }}" class="btn-primary btn-sm">{{ __('Edit') }}</a>
        @endunless
        <a href="{{ route('admin.expenses.index') }}" class="btn-secondary btn-sm">{{ __('Back') }}</a>
    </div>
</div>
@endsection
