<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyExpenseRequest;
use App\Models\CompanyExpense;
use App\Models\ExpenseCategory;
use App\Models\StudentPayment;
use App\Models\Supplier;
use App\Models\Vehicle;
use App\Services\AuditLogger;
use App\Support\DocumentNumber;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class ExpenseController extends Controller
{
    public function index(Request $request): View
    {
        $this->authorize('viewAny', CompanyExpense::class);

        $query = CompanyExpense::query()
            ->with(['category', 'vehicle', 'supplier'])
            ->when($request->filled('expense_category_id'), fn ($q) => $q->where('expense_category_id', $request->integer('expense_category_id')))
            ->when($request->filled('vehicle_id'), fn ($q) => $q->where('vehicle_id', $request->integer('vehicle_id')))
            ->when($request->filled('supplier_id'), fn ($q) => $q->where('supplier_id', $request->integer('supplier_id')))
            ->when($request->filled('payment_method'), fn ($q) => $q->where('payment_method', $request->string('payment_method')))
            ->when($request->filled('date_from'), fn ($q) => $q->whereDate('expense_date', '>=', $request->date('date_from')))
            ->when($request->filled('date_to'), fn ($q) => $q->whereDate('expense_date', '<=', $request->date('date_to')))
            ->when($request->filled('search'), function ($q) use ($request) {
                $term = '%'.$request->string('search')->trim().'%';
                $q->where(fn ($sub) => $sub->where('description', 'like', $term)->orWhere('expense_number', 'like', $term));
            });

        $income = StudentPayment::query()
            ->when($request->filled('date_from'), fn ($q) => $q->whereDate('payment_date', '>=', $request->date('date_from')))
            ->when($request->filled('date_to'), fn ($q) => $q->whereDate('payment_date', '<=', $request->date('date_to')))
            ->sum('amount');

        $expenseTotal = (float) (clone $query)->sum('amount');

        return view('admin.expenses.index', [
            'expenses' => (clone $query)->orderByDesc('expense_date')->orderByDesc('id')->paginate(20)->withQueryString(),
            'categories' => ExpenseCategory::orderBy('sort_order')->get(),
            'vehicles' => Vehicle::orderBy('vehicle_number')->get(['id', 'vehicle_number', 'plate_number']),
            'suppliers' => Supplier::orderBy('name')->get(['id', 'name']),
            'totals' => [
                'income' => (float) $income,
                'expenses' => $expenseTotal,
                'net' => round((float) $income - $expenseTotal, 2),
            ],
        ]);
    }

    public function create(): View
    {
        $this->authorize('create', CompanyExpense::class);

        return view('admin.expenses.form', [
            'expense' => new CompanyExpense(['expense_date' => now()->toDateString(), 'payment_method' => 'cash']),
            'categories' => ExpenseCategory::where('is_active', true)->orderBy('sort_order')->get(),
            'vehicles' => Vehicle::orderBy('vehicle_number')->get(),
            'suppliers' => Supplier::active()->orderBy('name')->get(),
        ]);
    }

    public function store(CompanyExpenseRequest $request): RedirectResponse
    {
        $this->authorize('create', CompanyExpense::class);

        $expense = DB::transaction(function () use ($request) {
            $expense = CompanyExpense::create([
                ...$request->validated(),
                'expense_number' => DocumentNumber::next(CompanyExpense::class, 'expense_number', 'EXP'),
                'created_by' => $request->user()->id,
            ]);

            AuditLogger::created($expense, "Expense {$expense->expense_number} of {$expense->amount} recorded");

            return $expense;
        });

        return redirect()->route('admin.expenses.index')->with('status', __('Expense recorded.'));
    }

    public function show(CompanyExpense $expense): View
    {
        $this->authorize('view', $expense);

        return view('admin.expenses.show', [
            'expense' => $expense->load(['category', 'vehicle', 'supplier', 'companyDebt', 'debtPayment', 'creator']),
        ]);
    }

    public function edit(CompanyExpense $expense): View
    {
        $this->authorize('update', $expense);

        // Expenses generated by a debt payment mirror that payment and must be
        // changed through the debt, never edited on their own.
        abort_if($expense->is_system_generated, 403, __('This expense was generated by a debt payment and cannot be edited directly.'));

        return view('admin.expenses.form', [
            'expense' => $expense,
            'categories' => ExpenseCategory::where('is_active', true)->orderBy('sort_order')->get(),
            'vehicles' => Vehicle::orderBy('vehicle_number')->get(),
            'suppliers' => Supplier::active()->orderBy('name')->get(),
        ]);
    }

    public function update(CompanyExpenseRequest $request, CompanyExpense $expense): RedirectResponse
    {
        $this->authorize('update', $expense);

        abort_if($expense->is_system_generated, 403, __('This expense was generated by a debt payment and cannot be edited directly.'));

        $original = $expense->getOriginal();
        $expense->update($request->validated());
        AuditLogger::updated($expense, "Expense {$expense->expense_number} updated", $original);

        return redirect()->route('admin.expenses.index')->with('status', __('Expense updated.'));
    }

    public function destroy(CompanyExpense $expense): RedirectResponse
    {
        $this->authorize('delete', $expense);

        abort_if($expense->is_system_generated, 403, __('Reverse the debt payment instead of deleting this expense.'));

        $number = $expense->expense_number;
        $expense->delete();
        AuditLogger::log('expense.deleted', $expense, "Expense {$number} removed");

        return back()->with('status', __('Expense removed.'));
    }
}
